"""Variable-aware date parsing for the Indo-VAP clinical dataset.

The Indo-VAP Excel sheets store dates in **five** distinct ways:

1. **Excel datetime cells** — openpyxl / pandas parse these into Python
   ``datetime`` objects automatically.  No ambiguity.
2. **Separator-delimited text strings** — stored as plain text in the cell,
   using ``/``, ``-``, or ``.`` as the field separator.
   The date *order* (month-first vs day-first) **varies per variable**:

   * **Most variables** use US-style **M/D/YYYY** or **M/D/YY**
     (e.g. ``"08/12/2014 12:27:48 PM"``, ``"7.28.14"``).
   * **Six specific variables** use Indian-style **D/M/YYYY** or **D/M/YY**
     (e.g. ``IC_VISDAT="28/05/2014"``, ``IT_IGRADAT="12.12.12"``).

   The canonical set of day-first variables is maintained in
   :data:`DMY_VARIABLES` below.

3. **ISO datetime strings** — ``"2014-07-28"`` or ``"2014-07-28 00:00:00"``.
   Unambiguous; year-month-day order.  **Tried before separator-delimited so
   ``YYYY-MM-DD`` is never mis-routed to the separator branch.**

4. **Compact integer dates** — 6, 7, or 8 pure digits stored as strings or
   integers (e.g. ``"20140728"`` for YYYYMMDD, ``"28052014"`` for DDMMYYYY,
   ``"07282014"`` for MMDDYYYY, ``"280514"`` for DDMMYY).  Locale resolution
   follows the same priority as the separator branch (DMY allowlist →
   manifest → heuristic → raise on ambiguous).  Output is always normalised
   to ISO ``YYYY-MM-DD``.

This module provides:

* :func:`parse_date` — parse any of the above into a ``datetime``.
* :func:`value_looks_like_date` — quick check for date-like strings.
* :func:`is_dmy_variable` — check if a variable uses D/M order.
* :func:`check_locale_consistency` — warn on DMY_VARIABLES/manifest conflicts.

All functions are pure (no side effects) and safe to call from any module.

Generated by scanning all 44 raw Excel files (2026-03-25).
"""

# SHARED UTILITY (Note 20 Gap C / Note 19): stays in scripts/, imported
# read-only by plugin skills; never moved into a skill, never imports from
# plugins/.

from __future__ import annotations

import logging
import re
from datetime import datetime
from typing import NamedTuple

__all__ = [
    "DMY_VARIABLES",
    "_NUM_DATE_RE",
    "_SEP_RE",
    "ParsedDate",
    "_disambiguate_locale",
    "check_locale_consistency",
    "is_dmy_variable",
    "parse_date",
    "value_looks_like_date",
]

_log = logging.getLogger(f"report_ai_portal.{__name__}")

# ============================================================================
# Per-variable date order — D/M (day-first) variables
# ============================================================================
# The Indo-VAP Excel sheets are inconsistent: most text-string dates use
# US-style M/D/YYYY (month first), but a handful of variables use Indian-style
# D/M/YYYY (day first).  We determined this by scanning ALL rows in ALL 44
# Excel files: if any cell in a column has group1 > 12, that column MUST be
# day-first.  The 6 confirmed D/M variables are listed below.
#
# All other text-string date variables use M/D order (US-style) or are
# ambiguous (both parts ≤ 12) — those default to M/D.
#
# Excel-datetime columns (openpyxl parses to Python datetime) have no
# ambiguity — they are already typed objects.
#
# Verified by scanning all 44 raw Excel files (2026-03-25).

DMY_VARIABLES: frozenset[str] = frozenset(
    {
        "CBC_HBADAT",  # 5_CBC.xlsx            e.g. "25/09/2017"
        "CC_VISDAT",  # 14_Case_Control.xlsx   e.g. "25/08/2015"
        "FOA_VISDAT",  # 98A_FOA.xlsx           e.g. "19/02/2015"
        "FOB_VISDAT",  # 98B_FOB.xlsx           e.g. "24/07/2015"
        "IC_VISDAT",  # 2A_ICBaseline.xlsx     e.g. "28/05/2014"
        "IT_IGRADAT",  # 11_IGRA.xlsx           e.g. "12/12/12" (D/M/YY, 2-digit year)
    }
)
"""Variable names whose slash-date text strings use D/M/YYYY (day first, Indian).

All other slash-date variables default to M/D/YYYY (month first, US).
"""


# ============================================================================
# Compiled regexes
# ============================================================================

# ISO: YYYY-MM-DD [HH:MM:SS]
# Must be tried FIRST so "2014-07-28" is never routed to the separator branch.
# Month/day accept 1-2 digits (non-zero-padded "2014-3-5" is valid); the
# datetime() construction in parse_date validates the actual ranges, so the
# regex stays permissive rather than rejecting real dates on formatting alone.
_ISO_RE = re.compile(
    r"^((?:19|20)\d{2})-(\d{1,2})-(\d{1,2})"
    r"(?:[ T](\d{1,2}):(\d{2}):(\d{2}))?$"
)

# Separator-delimited: A<sep>B<sep>C [H:M:S [AM|PM]]
# Accepts / (slash), - (hyphen), or . (dot) as the separator.  All three must
# use the SAME separator within a single value (enforced by backreference \2).
# Groups: (1)=first, (2)=sep char, (3)=second, (4)=year,
#         (5)=hour, (6)=min, (7)=sec, (8)=AM/PM
# NOTE: ISO "YYYY-MM-DD" is already intercepted by _ISO_RE above, so when this
# regex matches a hyphen-delimited value the year in group-4 is always ≤ 4
# digits — but we guard in the parser anyway by checking _ISO_RE first.
_SEP_RE = re.compile(
    r"^(\d{1,2})([/.\-])(\d{1,2})\2(\d{2,4})"
    r"(?:\s+(\d{1,2}):(\d{2}):(\d{2})(?:\s*([AP]M))?)?$",
    re.I,
)

# Quick detection: matches any separator-delimited date with optional time.
# Used only for value_looks_like_date() — does not need to distinguish ISO.
# NOTE: the separator characters in each component need not match (e.g.
# "28/05-2014" passes this check) — mixed-separator strings are caught and
# rejected by _SEP_RE's backreference in the actual parser.
_SLASH_DETECT_RE = re.compile(
    r"^\d{1,2}[/.\-]\d{1,2}[/.\-]\d{2,4}(?:\s+\d{1,2}:\d{2}:\d{2}(?:\s*[AP]M)?)?$",
    re.I,
)

# Quick detection: ISO date
_ISO_DETECT_RE = re.compile(
    r"^(?:19|20)\d{2}-\d{1,2}-\d{1,2}"
    r"(?:[ T]\d{1,2}:\d{2}:\d{2})?$"
)

# Compact integer date: 6, 7, or 8 pure digits (no separators).
# 8-digit: YYYYMMDD / DDMMYYYY / MMDDYYYY
# 7-digit: DMMYYYY (1+2+4) or DDMYYYY (2+1+4)  — day-first study only
# 6-digit: DDMMYY (2+2+2)
_NUM_DATE_RE = re.compile(r"^(\d{6,8})$")


# ============================================================================
# Data structures
# ============================================================================


class ParsedDate(NamedTuple):
    """Result of parsing a date string."""

    dt: datetime
    """The parsed datetime. Time component is always ``00:00:00``; the original
    string's time is intentionally discarded for date-granularity anonymization
    (see ``has_time`` and ``ampm`` for source-layout metadata)."""

    has_time: bool
    """True if the original string included a time component."""

    ampm: str | None
    """'AM' or 'PM' if present in the original, else None."""

    format: str
    """One of 'iso', 'mdy', 'dmy' indicating the detected source format."""

    original: str
    """The original (stripped) string that was parsed."""


# ============================================================================
# Variable-name lookup
# ============================================================================


# Precomputed upper-cased set for O(1) case-insensitive lookup
_DMY_UPPER: frozenset[str] = frozenset(v.upper() for v in DMY_VARIABLES)


def is_dmy_variable(field_name: str) -> bool:
    """Return True if *field_name* is known to use D/M (day-first) date order.

    Checks against the canonical ``DMY_VARIABLES`` frozenset defined in
    this module.  The comparison is **case-insensitive** so that column
    name variants (e.g. ``ic_visdat``, ``IC_VISDAT``, ``Ic_VisDat``) all
    resolve identically.
    """
    return field_name.upper() in _DMY_UPPER


def _disambiguate_locale(value: str, *, declared_locale: str | None = None) -> str | None:
    """Attempt to determine whether *value* is in DMY or MDY format.

    Args:
        value: A separator-delimited date string like ``"28/05/2014"``,
               ``"28-05-2014"``, or ``"05.28.2014"``.  Only the first two
               numeric components (before the year) are inspected.
        declared_locale: If provided (``"DMY"`` or ``"MDY"``), return it
                         immediately without inspecting *value*.

    Returns:
        ``"DMY"`` if the first component must be the day,
        ``"MDY"`` if the second component must be the day, or
        ``None`` if both components are ≤ 12 (genuinely ambiguous).

    Raises:
        ValueError: If both numeric components exceed 12 (impossible as either
                    month or day).
    """
    if declared_locale is not None:
        return declared_locale

    # Accept /, -, or . as separator (ISO YYYY-MM-DD is caught by _ISO_RE first).
    m = _SEP_RE.match(value.strip())
    if not m:
        return None

    # Groups: (1)=first_component, (2)=sep, (3)=second_component, (4)=year
    g1, g2 = int(m.group(1)), int(m.group(3))

    if g1 > 12 and g2 > 12:
        raise ValueError(f"Invalid date string: {value!r} (both components exceed 12)")

    if g1 > 12:
        # First component cannot be a month → it must be the day → DMY
        return "DMY"
    if g2 > 12:
        # Second component cannot be a month → it must be the day → MDY
        return "MDY"

    # Both ≤ 12: cannot determine locale from value alone
    return None


# ============================================================================
# PHI-safe value masking (for logs and exception messages only)
# ============================================================================


def _mask_date_value(value: str) -> str:
    """Return a PHI-safe shape of *value* for logs and error messages.

    Digits → ``9``, ASCII letters → ``X``, separator characters kept.

    Note: mirrors ``scripts.security.phi_patterns.mask_date_shape``.  A direct
    import is not possible because ``scripts.security.__init__`` imports
    ``phi_scrub``, which imports ``scripts.extraction.io``, creating a circular
    dependency.  If the masking contract changes, update both implementations.
    """
    result: list[str] = []
    for ch in value:
        if ch.isdigit():
            result.append("9")
        elif ch.isascii() and ch.isalpha():
            result.append("X")
        else:
            result.append(ch)
    return "".join(result)


# ============================================================================
# Locale resolution helper
# ============================================================================


def _resolve_locale(
    field_name: str | None,
    date_locales: dict[str, str] | None,
) -> str | None:
    """Resolve date locale for *field_name* using the canonical priority chain.

    Priority (first match wins):
    1. :func:`is_dmy_variable` allowlist (case-insensitive) → ``"DMY"``.
    2. ``date_locales`` manifest override (keys already normalised to
       UPPER-CASE at manifest load time) → declared value.
    3. Returns ``None`` — caller applies value heuristic / fail-closed raise.

    Args:
        field_name: Column/variable name, or ``None`` for unknown field.
        date_locales: Per-column locale overrides with UPPER-CASE keys
                      (normalised once when the manifest is loaded by
                      :func:`dataset_pipeline.check_forms_manifest`).
                      May be ``None`` or empty.

    Returns:
        ``"DMY"``, ``"MDY"``, or ``None`` (locale not yet determined).
    """
    if field_name is None:
        return None

    # P1: canonical DMY allowlist (O(1) via precomputed _DMY_UPPER)
    field_upper = field_name.upper()
    if field_upper in _DMY_UPPER:
        return "DMY"

    # P2: manifest per-column override (keys are UPPER-CASE; single O(1) lookup)
    if date_locales:
        declared = date_locales.get(field_upper)
        if declared is not None:
            return declared

    return None


# ============================================================================
# Import-time consistency check
# ============================================================================


def check_locale_consistency(date_locales: dict[str, str]) -> None:
    """Emit a WARNING for columns that appear in both DMY_VARIABLES and the manifest
    with a conflicting locale.

    Call this once after loading the manifest's ``date_locales`` mapping (e.g.
    from :func:`dataset_pipeline.check_forms_manifest`).  The function performs
    no parsing — it is a sanity check only and never raises.

    A *conflict* is a column whose UPPER-CASE name is in :data:`_DMY_UPPER`
    (so the allowlist would resolve it to ``"DMY"``) but whose manifest entry
    declares ``"MDY"`` (or vice versa).  The allowlist wins at parse time;
    this warning surfaces the inconsistency so the operator can reconcile the
    manifest.

    Args:
        date_locales: Per-column locale overrides with UPPER-CASE keys
                      (as normalised by :func:`dataset_pipeline.check_forms_manifest`).
    """
    for col_upper, declared in date_locales.items():
        if col_upper in _DMY_UPPER and declared.upper() != "DMY":
            _log.warning(
                "Locale conflict: column %r is in the DMY_VARIABLES allowlist "
                "(resolved to DMY at parse time) but _forms_manifest.yaml declares %r. "
                "Allowlist takes precedence; update the manifest to 'DMY' or remove "
                "the column from DMY_VARIABLES to resolve.",
                col_upper,
                declared,
            )


# ============================================================================
# Core parser
# ============================================================================


def _expand_year(y: int) -> int:
    """Expand a 2-digit year: <50 → 2000+, ≥50 → 1900+.  4-digit unchanged."""
    if y < 100:
        return 2000 + y if y < 50 else 1900 + y
    return y


def parse_date(
    value: str,
    *,
    field_name: str | None = None,
    date_locales: dict[str, str] | None = None,
    default_locale: str | None = None,
) -> ParsedDate | None:
    """Parse a date/datetime text string into a :class:`ParsedDate`.

    Accepted formats (tried in order):

    1. ISO ``YYYY-MM-DD`` (with optional ``HH:MM:SS``) — unambiguous.
    2. Separator-delimited ``A<sep>B<sep>C`` where *sep* is ``/``, ``-``, or
       ``.`` (all three separators within a single value must be the same).
       Locale (DMY vs MDY) is resolved via the priority chain below.
    3. Compact integer:

       * **8-digit** ``DDMMYYYY`` / ``MMDDYYYY`` — locale resolved via priority
         chain; YYYYMMDD is tried as a last resort when the locale-resolved
         parse yields an invalid date.
       * **7-digit** ``DMMYYYY`` or ``DDMYYYY`` — both layouts tried for EACH
         locale direction; exactly one must be valid (ambiguous → ``None``).
       * **6-digit** ``DDMMYY`` — defaults day-first (Indian study); 2-digit
         year expanded by :func:`_expand_year`.

    Locale-resolution priority for separator and compact formats:

    1. :func:`is_dmy_variable` allowlist (case-insensitive) → **DMY**.
    2. ``date_locales`` manifest override (UPPER-CASE keys) → declared.
    3. Value heuristic: first component > 12 → DMY; second > 12 → MDY.
    4. ``default_locale`` study-wide origin default (e.g. ``"DMY"`` for an
       Indian-origin study) — applied ONLY when steps 1-3 are inconclusive,
       so explicit declarations and provably-decisive values always win.
    5. Still ambiguous with ``field_name`` known and no ``default_locale`` →
       :class:`ValueError` (fail-closed; caller quarantines the row).

    Args:
        value: The raw text string (e.g. ``"7/28/14"``, ``"28.05.2014"``,
               ``"28052014"``, ``"2014-07-28 00:00:00"``).
        field_name: The column/variable name the value came from.  Used to
                    determine M/D vs D/M order.  If ``None``, defaults to
                    M/D (US-style) when unambiguous and raises on genuinely
                    ambiguous values.
        date_locales: Optional per-column locale overrides loaded from the
                      study's ``_forms_manifest.yaml`` ``date_locales:``
                      section.  Keys must be UPPER-CASE (normalised by
                      :func:`dataset_pipeline.check_forms_manifest`).
                      Values are ``"DMY"`` or ``"MDY"``.
                      Takes precedence over the heuristic.
        default_locale: Study-wide origin default (``"DMY"``/``"MDY"``) applied
                      only when the allowlist, manifest, and value heuristic are
                      all inconclusive — i.e. an ambiguous value in an undeclared
                      column. ``None`` (default) preserves the fail-closed raise.

    Returns:
        A :class:`ParsedDate` on success, or ``None`` if the string cannot
        be parsed as a date.

    Raises:
        ValueError: If the separator/compact-date locale cannot be determined
                    (both components ≤ 12, no manifest entry, field known).

    Examples::

        >>> parse_date("7/28/14")
        ParsedDate(dt=datetime(2014, 7, 28), ..., format='mdy', ...)

        >>> parse_date("28.05.2014", field_name="IC_VISDAT")
        ParsedDate(dt=datetime(2014, 5, 28), ..., format='dmy', ...)

        >>> parse_date("28-05-2014", field_name="IC_VISDAT")
        ParsedDate(dt=datetime(2014, 5, 28), ..., format='dmy', ...)

        >>> parse_date("28072014", field_name="IC_VISDAT")
        ParsedDate(dt=datetime(2014, 7, 28), ..., format='iso', ...)

        >>> parse_date("2014-07-28 00:00:00")
        ParsedDate(dt=datetime(2014, 7, 28), ..., format='iso', ...)
    """
    value = value.strip()
    if not value:
        return None

    # ── Try ISO: YYYY-MM-DD [HH:MM:SS] ──
    # Must run BEFORE the separator branch so "2014-07-28" is never
    # mis-routed to the hyphen-separator path.
    m = _ISO_RE.match(value)
    if m:
        y, mo, d = int(m.group(1)), int(m.group(2)), int(m.group(3))
        try:
            dt = datetime(y, mo, d)
        except (ValueError, OverflowError):
            return None
        return ParsedDate(
            dt=dt,
            has_time=m.group(4) is not None,
            ampm=None,
            format="iso",
            original=value,
        )

    # ── Try separator-delimited: A<sep>B<sep>C [H:M:S [AM/PM]] ──
    # Accepts / (slash), - (hyphen), or . (dot) as the field separator.
    # The backreference \2 in _SEP_RE enforces that all three separators
    # within a single value are identical.
    m = _SEP_RE.match(value)
    if m:
        # Groups: (1)=first, (2)=sep_char, (3)=second, (4)=year,
        #         (5)=hour, (6)=min, (7)=sec, (8)=AM/PM
        g1, g3 = int(m.group(1)), int(m.group(3))
        g_year = int(m.group(4))
        y = _expand_year(g_year)

        # ── Determine locale (DMY vs MDY) ──
        # Priority order: DMY allowlist → manifest override → value heuristic
        locale: str | None = _resolve_locale(field_name, date_locales)

        if locale is None:
            # Try to resolve from the value itself
            locale = _disambiguate_locale(value)  # may raise ValueError for invalid

            if locale is None:
                # Genuinely ambiguous (both components ≤ 12)
                if default_locale is not None:
                    # Study-origin default (e.g. DMY for an Indian study) — applied
                    # only after the allowlist/manifest/heuristic are inconclusive.
                    locale = default_locale
                elif field_name is not None:
                    raise ValueError(
                        f"Ambiguous date locale for column {field_name!r}: "
                        "declare in _forms_manifest.yaml under date_locales: "
                        f"(values like {_mask_date_value(value)!r} have both components ≤ 12)"
                    )
                else:
                    # No field_name → legacy fall-through: default MDY (no raise)
                    locale = "MDY"
            else:
                if field_name is not None:
                    _log.info(
                        "Date locale for %r disambiguated heuristically to %s "
                        "(value shape %s); declare in _forms_manifest.yaml to silence",
                        field_name,
                        locale,
                        _mask_date_value(value),
                    )

        dmy = locale == "DMY"
        if dmy:
            # D/M/Y: group1=day, group3=month
            day, month = g1, g3
            fmt = "dmy"
        else:
            # M/D/Y: group1=month, group3=day
            month, day = g1, g3
            fmt = "mdy"

        try:
            dt = datetime(y, month, day)
        except (ValueError, OverflowError):
            return None
        if not (1900 <= y <= 2100):
            # L1 guard (same class as the 8-digit year-range guard): a 3-digit or
            # otherwise implausible year (e.g. "28/05/100" → 100) is not a real
            # clinical date — return None so the caller quarantines it rather than
            # emitting a structurally-wrong year. Valid 2-digit years expand to
            # 1900-2099 and 4-digit years in [1900, 2100] are unaffected.
            return None

        ampm = m.group(8).upper() if m.group(8) else None
        return ParsedDate(
            dt=dt,
            has_time=m.group(5) is not None,
            ampm=ampm,
            format=fmt,
            original=value,
        )

    # ── Try compact integer date: 6, 7, or 8 pure digits ──
    m = _NUM_DATE_RE.match(value)
    if m:
        s = m.group(1)
        # ny/nmo/nd are used as local ints to avoid shadowing the separator-branch
        # names (y, mo, d) which mypy tracks even across branches.
        ny: int
        nmo: int
        nd: int

        if len(s) == 8:
            # ── 8-digit ──────────────────────────────────────────────────────
            # Step 1: If the first four digits form a plausible year (1900-2100)
            # try YYYYMMDD first.  For this study the scan proved no 8-digit
            # dates are YYYYMMDD (all start with a day/month pair, not a year),
            # but we keep the YYYYMMDD path as a last-resort safety net for
            # values that cannot be interpreted under any DMY/MDY reading.
            #
            # NOTE: We do NOT attempt YYYYMMDD as the *preferred* path; instead
            # we resolve locale (DMY/MDY) first and only fall back to YYYYMMDD
            # when the locale-resolved parse yields an invalid datetime.

            # Resolve locale first (same priority as separator branch).
            locale_int: str | None = _resolve_locale(field_name, date_locales)

            if locale_int is None:
                # Try value-level disambiguation from the two leading 2-char groups.
                d_cand, mo_cand = int(s[0:2]), int(s[2:4])
                if d_cand > 12 and mo_cand > 12:
                    # Both exceed 12 — impossible under DDMM or MMDD layout.
                    # Try YYYYMMDD as last resort.
                    y_try = int(s[0:4])
                    if 1900 <= y_try <= 2100:
                        try:
                            dt = datetime(y_try, int(s[4:6]), int(s[6:8]))
                            return ParsedDate(
                                dt=dt,
                                has_time=False,
                                ampm=None,
                                format="iso",
                                original=value,
                            )
                        except (ValueError, OverflowError):
                            pass
                    return None
                if d_cand > 12:
                    locale_int = "DMY"
                elif mo_cand > 12:
                    locale_int = "MDY"
                else:
                    # Genuinely ambiguous
                    if default_locale is not None:
                        # Study-origin default (e.g. DMY for an Indian study).
                        locale_int = default_locale
                    elif field_name is not None:
                        raise ValueError(
                            f"Ambiguous integer date locale for column {field_name!r}: "
                            "declare in _forms_manifest.yaml under date_locales: "
                            f"(value {_mask_date_value(value)!r} has both leading components ≤ 12)"
                        )
                    else:
                        # No field_name → legacy fall-through: default MDY
                        locale_int = "MDY"
                if field_name is not None:
                    _log.info(
                        "Integer date locale for %r disambiguated heuristically to %s "
                        "(value shape %s); declare in _forms_manifest.yaml to silence",
                        field_name,
                        locale_int,
                        _mask_date_value(value),
                    )

            if locale_int == "DMY":
                nd, nmo, ny = int(s[0:2]), int(s[2:4]), int(s[4:8])
            else:  # MDY
                nmo, nd, ny = int(s[0:2]), int(s[2:4]), int(s[4:8])

            try:
                dt = datetime(ny, nmo, nd)
                if not (1900 <= ny <= 2100):
                    # H1 guard: the locale-resolved split produced a structurally
                    # implausible year — e.g. "20030612" → DMY → year int("0612")=612,
                    # which datetime() accepts (MINYEAR=1) and would silently emit as a
                    # medieval year. Discard and fall through to the YYYYMMDD last resort
                    # below instead of publishing a corrupted date.
                    raise ValueError("resolved year outside plausible range [1900, 2100]")
            except (ValueError, OverflowError):
                # Locale-resolved parse failed or yielded an implausible year; try
                # YYYYMMDD as last resort.
                y_try = int(s[0:4])
                if 1900 <= y_try <= 2100:
                    try:
                        dt = datetime(y_try, int(s[4:6]), int(s[6:8]))
                        return ParsedDate(
                            dt=dt,
                            has_time=False,
                            ampm=None,
                            format="iso",
                            original=value,
                        )
                    except (ValueError, OverflowError):
                        pass
                return None

        elif len(s) == 7:
            # ── 7-digit: canonical-first, alternate-fallback split ───────────
            # A 7-digit integer date arises when a single-digit field (day or
            # month) is written without a leading zero. With an explicit/derived
            # locale, two layouts are physically possible for human-entered
            # numeric dates (e.g. clinical specimen forms where a clerk typed a
            # bare number):
            #   DMY canonical (1+2+4)  DMMYYYY  d=s[0:1], m=s[1:3]  (e.g. 5/12/2014 → "5122014")
            #   DMY alternate (2+1+4)  DDMYYYY  d=s[0:2], m=s[2:3]  (e.g. 15/8/2014 → "1582014")
            #   MDY canonical (1+2+4)  MDDYYYY  m=s[0:1], d=s[1:3]
            #   MDY alternate (2+1+4)  MMDYYYY  m=s[0:2], d=s[2:3]
            # In every split the year is s[3:7]. We try the CANONICAL split
            # first (this preserves the both-valid recovery, e.g. "1052014" →
            # 1 May under DMY) and fall back to the ALTERNATE split only when the
            # canonical yields an invalid calendar date (recovers real dates like
            # "1582014" → 15 Aug, "1392014" → 13 Sep). A value invalid under BOTH
            # splits is genuinely bad → quarantine (fail-closed). (Note 29 — the
            # earlier "2+1+4 is a phantom" assumption held only for int-truncation
            # of zero-padded values, not for human-entered numeric dates.)

            # Resolve locale (DMY allowlist → manifest override → origin default).
            locale_7: str | None = _resolve_locale(field_name, date_locales) or default_locale

            if locale_7 is not None:
                y7 = int(s[3:7])
                if not (1900 <= y7 <= 2100):
                    # Same year-range guard the separator + 8-digit branches apply.
                    return None
                dt7: datetime | None = None
                for _split in ("canonical", "alternate"):
                    try:
                        if locale_7 == "DMY":
                            if _split == "canonical":  # DMMYYYY: d=s[0:1], m=s[1:3]
                                dt7 = datetime(y7, int(s[1:3]), int(s[0:1]))
                            else:  # DDMYYYY: d=s[0:2], m=s[2:3]
                                dt7 = datetime(y7, int(s[2:3]), int(s[0:2]))
                        else:  # MDY
                            if _split == "canonical":  # MDDYYYY: m=s[0:1], d=s[1:3]
                                dt7 = datetime(y7, int(s[0:1]), int(s[1:3]))
                            else:  # MMDYYYY: m=s[0:2], d=s[2:3]
                                dt7 = datetime(y7, int(s[0:2]), int(s[2:3]))
                    except (ValueError, OverflowError):
                        dt7 = None
                        continue
                    break
                if dt7 is None:
                    return None
                # Bind the shared `dt` consumed by the ParsedDate return below
                # (the 8-digit and 6-digit branches set it analogously).
                dt = dt7
            else:
                # No explicit locale: try both DMY layouts and pick unambiguous winner.
                # DMMYYYY: d=s[0], m=s[1:3], y=s[3:7]
                dt_dmmyyyy: datetime | None = None
                try:
                    dt_dmmyyyy = datetime(int(s[3:7]), int(s[1:3]), int(s[0:1]))
                except (ValueError, OverflowError):
                    dt_dmmyyyy = None

                # DDMYYYY: d=s[0:2], m=s[2:3], y=s[3:7]
                dt_ddmyyyy: datetime | None = None
                try:
                    dt_ddmyyyy = datetime(int(s[3:7]), int(s[2:3]), int(s[0:2]))
                except (ValueError, OverflowError):
                    dt_ddmyyyy = None

                valid_count = (dt_dmmyyyy is not None) + (dt_ddmyyyy is not None)
                if valid_count != 1:
                    # Both valid (ambiguous) or neither valid (invalid) → quarantine.
                    return None
                dt = dt_dmmyyyy if dt_dmmyyyy is not None else dt_ddmyyyy  # type: ignore[assignment]
                if not (1900 <= dt.year <= 2100):
                    # Same year-range guard the separator + 8-digit + explicit-locale
                    # 7-digit branches apply: a structurally-implausible resolved year
                    # (e.g. "1130615" → year 615, where s[3:7] is not a real year) is
                    # quarantined rather than emitted as a corrupted medieval date.
                    return None
                nd, nmo, ny = dt.day, dt.month, dt.year

        else:
            # ── 6-digit: DDMMYY ──────────────────────────────────────────────
            # Split: d=s[0:2], m=s[2:4], yy=s[4:6]; expand yy → 4-digit year.
            # Locale resolution follows the SAME precedence as the separator and
            # 8-digit branches: DMY allowlist → manifest → value heuristic →
            # fail-closed (raise) on a genuinely-ambiguous KNOWN field; for an
            # unknown field (field_name=None, non-production/legacy) it falls back
            # to MDY exactly like the other branches. The study's "all day-first"
            # assumption is encoded in the manifest/allowlist declarations, NOT a
            # silent code default, so a genuinely-MDY column is never silently
            # day/month-swapped.
            locale_6: str | None = _resolve_locale(field_name, date_locales)

            if locale_6 is None:
                # Heuristic: if first 2 digits > 12 → must be day (DMY).
                # If second pair > 12 → MDY.  Both ≤ 12: genuinely ambiguous.
                d6, m6 = int(s[0:2]), int(s[2:4])
                if d6 > 12 and m6 > 12:
                    return None  # Impossible regardless of layout.
                if d6 > 12:
                    locale_6 = "DMY"
                elif m6 > 12:
                    locale_6 = "MDY"
                else:
                    # Genuinely ambiguous — apply the study-origin default if set
                    # (e.g. DMY for an Indian study), else fail-closed for a known
                    # field, IDENTICAL to the separator + 8-digit branches. Explicit
                    # manifest/allowlist declarations resolve BEFORE this heuristic,
                    # so a genuinely-MDY column is never silently day/month-swapped.
                    if default_locale is not None:
                        locale_6 = default_locale
                    elif field_name is not None:
                        raise ValueError(
                            f"Ambiguous 6-digit date locale for column {field_name!r}: "
                            "declare in _forms_manifest.yaml under date_locales: "
                            f"(value {_mask_date_value(value)!r} has both leading components ≤ 12)"
                        )
                    else:
                        # No field_name → legacy fall-through: default MDY (matches
                        # the separator + 8-digit branches).
                        locale_6 = "MDY"

            yy6 = _expand_year(int(s[4:6]))
            if locale_6 == "DMY":
                nd, nmo, ny = int(s[0:2]), int(s[2:4]), yy6
            else:  # MDY
                nmo, nd, ny = int(s[0:2]), int(s[2:4]), yy6

            try:
                dt = datetime(ny, nmo, nd)
            except (ValueError, OverflowError):
                return None

        # Integer dates are always normalised to ISO output (format='iso') so the
        # jittered value re-emits as YYYY-MM-DD via the existing _format_date path.
        return ParsedDate(
            dt=dt,
            has_time=False,
            ampm=None,
            format="iso",
            original=value,
        )

    return None


# ============================================================================
# Date detection
# ============================================================================


def value_looks_like_date(value: str) -> bool:
    """Return True if *value* looks like a date/datetime string.

    This is a quick check — it does NOT validate the date components.
    Matches ISO dates, separator-delimited dates (``/``, ``-``, ``.``),
    and compact integer dates (6-8 pure digits).
    """
    v = value.strip()
    return bool(_ISO_DETECT_RE.match(v) or _SLASH_DETECT_RE.match(v) or _NUM_DATE_RE.match(v))
