"""Phase 3 cross-verify emitter — gh pr/issue create with redactor-routed bodies.

Walks PR-draft JSONs and HITL-draft Markdowns, formats bodies through the
PHI redactor, and shells to ``gh pr create`` / ``gh issue create`` via an
injected runner.

Tests pass a mock runner; production wires the runner to ``subprocess.run``.
"""

from __future__ import annotations

import json
from collections.abc import Callable
from pathlib import Path
from typing import Any

import config
from scripts.security.phi_redactor import redact
from scripts.utils.logging_system import get_logger

logger = get_logger(__name__)

GHRunner = Callable[[list[str], "str | None"], int]


def _format_pr_body(fix: dict[str, Any], token: str, description: str) -> tuple[str, str]:
    form = fix.get("form", "?")
    kind = fix.get("kind", "?")
    title = f"cross-verify: {kind} for {form}/`{token}`"
    lines = [
        f"# Cross-verify auto-fix proposal: {kind}",
        "",
        f"**Form:** {form}",
        f"**Variable (token):** `{token}`",
        f"**Description:** {description or '(unknown)'}",
        "",
        "## Proposed change",
        "",
    ]
    if kind == "rule_add" and fix.get("rule_yaml"):
        lines += ["```yaml", str(fix["rule_yaml"]).rstrip(), "```"]
    elif kind == "sot_stub_add" and fix.get("variable_record"):
        lines += ["```yaml", json.dumps(fix["variable_record"], indent=2), "```"]
    else:
        lines.append("(see attached fix proposal)")
    lines += [
        "",
        "## Source",
        "",
        "Generated by `scripts/source_truth/cross_verify_fix_agent.py`. PHI variable ids",
        "are masked through `scripts/security/phi_redactor.redact`.",
        "",
    ]
    return title, "\n".join(lines)


def _redact_body_text(raw_body: str, variable_id: str, token: str) -> str:
    """Replace cleartext variable_id occurrences with the masked token.

    Substitutes both the bare ``variable_id`` and any ``form/variable_id``
    occurrences. When the redactor returns the cleartext (non-PHI variable),
    the substitution is a no-op.
    """
    if not variable_id or token == variable_id:
        return raw_body
    return raw_body.replace(variable_id, token)


def _format_issue_body(
    raw_body: str,
    form: str,
    variable_id: str,
    token: str,
    description: str,
) -> tuple[str, str]:
    title = f"cross-verify HITL: {form}/`{token}`"
    redacted_raw = _redact_body_text(raw_body, variable_id, token)
    lines = [
        f"# Cross-verify HITL: {form}/`{token}`",
        "",
        f"**Variable (token):** `{token}`",
        f"**Description:** {description or '(unknown)'}",
        "",
        "## Original draft",
        "",
        redacted_raw.strip(),
        "",
    ]
    return title, "\n".join(lines)


def _load_pr_drafts(pr_drafts_dir: Path) -> list[dict[str, Any]]:
    if not pr_drafts_dir.is_dir():
        return []
    out: list[dict[str, Any]] = []
    for f in sorted(pr_drafts_dir.glob("*.json")):
        try:
            body = json.loads(f.read_text())
        except json.JSONDecodeError:
            continue
        if not isinstance(body, dict):
            continue
        body["_path"] = f
        if "form" not in body or "variable_id" not in body:
            stem = f.stem  # e.g. "F_DROPPED_VAR"
            if "_" in stem:
                form, _, vid = stem.partition("_")
                body.setdefault("form", form)
                body.setdefault("variable_id", vid)
        out.append(body)
    return out


def _load_hitl_drafts(hitl_drafts_dir: Path) -> list[dict[str, Any]]:
    if not hitl_drafts_dir.is_dir():
        return []
    out: list[dict[str, Any]] = []
    for f in sorted(hitl_drafts_dir.glob("*.md")):
        if f.stem.endswith(".body"):
            continue
        text = f.read_text()
        stem = f.stem
        form, _, vid = stem.partition("_")
        out.append({"form": form, "variable_id": vid, "body": text, "_path": f})
    return out


def emit(
    *,
    pr_drafts_dir: Path | None = None,
    hitl_drafts_dir: Path | None = None,
    evidence_packs_dir: Path | None = None,
    gh_runner: GHRunner | None = None,
    key_path: Path | None = None,
) -> dict[str, Any]:
    """Walk drafts, format bodies through the redactor, invoke gh runner.

    Returns a summary dict with counters: ``pr_emitted``, ``issue_emitted``,
    ``skipped_no_runner``, ``failed``.

    When ``gh_runner`` is None, the emitter writes the formatted body to
    ``<draft_dir>/<draft_name>.body.md`` and skips the live call. This is the
    no-``gh`` dev / CI path.
    """
    pr_drafts_dir = (
        pr_drafts_dir if pr_drafts_dir is not None else config.CROSS_VERIFY_PR_DRAFTS_DIR
    )
    hitl_drafts_dir = (
        hitl_drafts_dir if hitl_drafts_dir is not None else config.CROSS_VERIFY_HITL_DRAFTS_DIR
    )
    evidence_packs_dir = (
        evidence_packs_dir
        if evidence_packs_dir is not None
        else config.LLM_SOURCE_EVIDENCE_PACKS_DIR
    )
    pr_emitted = 0
    issue_emitted = 0
    skipped_no_runner = 0
    failed = 0
    for fix in _load_pr_drafts(pr_drafts_dir):
        form = fix["form"]
        vid = fix["variable_id"]
        token, description = redact(
            form, vid, evidence_packs_dir=evidence_packs_dir, key_path=key_path
        )
        title, body = _format_pr_body(fix, token, description)
        body_path = fix["_path"].with_suffix(".body.md")
        body_path.write_text(body, encoding="utf-8")
        if gh_runner is None:
            skipped_no_runner += 1
            continue
        argv = ["pr", "create", "--title", title, "--body-file", "-"]
        rc = gh_runner(argv, body)
        if rc == 0:
            pr_emitted += 1
        else:
            failed += 1
            logger.warning("cross_verify_emit.pr_failed form=%s vid=%s rc=%d", form, vid, rc)
    for hitl in _load_hitl_drafts(hitl_drafts_dir):
        form = hitl["form"]
        vid = hitl["variable_id"]
        token, description = redact(
            form, vid, evidence_packs_dir=evidence_packs_dir, key_path=key_path
        )
        title, body = _format_issue_body(hitl["body"], form, vid, token, description)
        body_path = hitl["_path"].with_suffix(".body.md")
        body_path.write_text(body, encoding="utf-8")
        if gh_runner is None:
            skipped_no_runner += 1
            continue
        argv = [
            "issue",
            "create",
            "--label",
            "HITL",
            "--title",
            title,
            "--body-file",
            "-",
        ]
        rc = gh_runner(argv, body)
        if rc == 0:
            issue_emitted += 1
        else:
            failed += 1
            logger.warning("cross_verify_emit.issue_failed form=%s vid=%s rc=%d", form, vid, rc)
    summary = {
        "pr_emitted": pr_emitted,
        "issue_emitted": issue_emitted,
        "skipped_no_runner": skipped_no_runner,
        "failed": failed,
    }
    logger.info("cross_verify_emit.complete %s", summary)
    return summary
