"""Operationally untraceable staging removal with destruction attestation.

This module provides :func:`destroy_staging_and_attest`, the foundational
helper that securely removes the per-study AMBER-zone staging directory after
a successful publish and emits a destruction-attestation JSON that proves the
act happened.

It is intentionally narrow in scope: it accepts caller-supplied paths, calls
:func:`scripts.utils.secure_staging.secure_remove_tree`, verifies the result,
and writes an attestation file atomically. The full CLI wrapper (run/verify/
status subcommands) is wired in P3.1.

IRB-grade context:
    * HIPAA §164.310(c) — device + media controls: staged PHI is overwritten
      with random bytes and fsynced before unlink, then the tree is verified
      gone.
    * DPDPA 2023 §8(7) — erasure: the attestation record provides evidence
      of deletion.
    * APFS copy-on-write caveat: filesystem-level overwrite is performed;
      prior APFS snapshots or unreferenced blocks may persist until TRIM.
      Skill scope is operational untraceability, not forensic erasure.

Public API:
    * :class:`DestructionIncompleteError`
    * :func:`destroy_staging_and_attest`
"""

from __future__ import annotations

import json
import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path

from scripts.utils.secure_staging import secure_remove_tree

__all__ = [
    "DestructionIncompleteError",
    "destroy_staging_and_attest",
]

_APFS_COW_DISCLAIMER = (
    "Filesystem-level overwrite was performed via secrets.token_bytes + fsync; "
    "APFS copy-on-write means prior blocks may persist until trimmed. "
    "Skill scope is operational untraceability, not forensic erasure."
)

UTC = timezone.utc


class DestructionIncompleteError(Exception):
    """Raised when staging_dir still exists after secure_remove_tree.

    The CLI wrapper (P3.1) translates this to exit code 7.
    """


def destroy_staging_and_attest(
    *,
    study: str,
    run_id: str,
    staging_dir: Path,
    output_dir: Path,
) -> Path:
    """Securely remove staging_dir and emit a destruction-attestation JSON.

    Returns the path of the attestation file.

    Raises DestructionIncompleteError if staging_dir still exists after
    secure_remove_tree (exit code 7 for the wrapper that calls this).

    Args:
        study: Study name (e.g. "Indo-VAP"); used for paths and the
            attestation ``study`` field.
        run_id: Opaque run identifier provided by the caller; will be
            generated by the CLI wrapper in P3.1.
        staging_dir: The ``config.STUDY_STAGING_DIR / STUDY`` path to destroy.
        output_dir: The ``output/{STUDY}/`` root where
            ``runs/{run_id}/destruction_attestation.json`` should land.

    This function is ONLY invoked on a successful publish.  On any earlier
    pipeline failure the caller skips it so staging is preserved for
    inspection.  No "should I run?" guard lives here — that is the caller's
    contract.
    """
    staging_dir = Path(staging_dir)
    output_dir = Path(output_dir)

    # ------------------------------------------------------------------
    # a. Snapshot what's about to be destroyed BEFORE deletion.
    # ------------------------------------------------------------------
    removed_paths: list[str] = []
    if staging_dir.exists():
        for p in sorted(staging_dir.rglob("*")):
            if p.is_file():
                # Store relative path so the attestation is portable.
                try:
                    rel = p.relative_to(staging_dir)
                except ValueError:
                    rel = p
                removed_paths.append(str(rel))

    files_destroyed = len(removed_paths)

    # ------------------------------------------------------------------
    # b. Record destruction start timestamp.
    # ------------------------------------------------------------------
    started_utc = datetime.now(UTC).isoformat()

    # ------------------------------------------------------------------
    # c. Securely remove the tree.
    # ------------------------------------------------------------------
    secure_remove_tree(staging_dir)

    # ------------------------------------------------------------------
    # d. Verify the tree is gone.
    # ------------------------------------------------------------------
    if staging_dir.exists():
        raise DestructionIncompleteError(
            f"staging_dir still exists after secure_remove_tree: {staging_dir}"
        )

    # ------------------------------------------------------------------
    # e. Record destruction completion timestamp.
    # ------------------------------------------------------------------
    completed_utc = datetime.now(UTC).isoformat()

    # ------------------------------------------------------------------
    # f. Write attestation atomically (write to .tmp sibling, then rename).
    # ------------------------------------------------------------------
    attest_dir = output_dir / "runs" / run_id
    attest_dir.mkdir(parents=True, exist_ok=True)
    attest_path = attest_dir / "destruction_attestation.json"

    payload = {
        "apfs_cow_disclaimer": _APFS_COW_DISCLAIMER,
        "completed_utc": completed_utc,
        "cryptographic_erasure": False,
        "files_destroyed": files_destroyed,
        "removed_paths": removed_paths,
        "run_id": run_id,
        "staging_path": str(staging_dir),
        "started_utc": started_utc,
        "study": study,
    }
    serialised = json.dumps(payload, indent=2, sort_keys=True)

    tmp_fd, tmp_name = tempfile.mkstemp(
        dir=attest_dir,
        prefix=".destruction_attestation_",
        suffix=".tmp",
    )
    try:
        try:
            os.write(tmp_fd, serialised.encode("utf-8"))
            os.fsync(tmp_fd)
        finally:
            os.close(tmp_fd)
        Path(tmp_name).replace(attest_path)
    except Exception:
        # Best-effort cleanup of the .tmp file on error.
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise

    # ------------------------------------------------------------------
    # g. Return the attestation file path.
    # ------------------------------------------------------------------
    return attest_path
